--- name:default
# no documentation available for this property
aps_region_interest:
  aps_roi_start_column: 0
  aps_roi_start_row: 0
  aps_roi_end_column: 0
  aps_roi_end_row: 0
  state: false
  name: ''
# no documentation available for this property
davis_biases_1:
  PrBp_coarse: 2
  PrBp_fine: 58
  PrSFBp_coarse: 1
  PrSFBp_fine: 33
  state: false
  name: ''
# no documentation available for this property
davis_biases_2:
  DiffBn_coarse: 4
  DiffBn_fine: 39
  ONBn_coarse: 6
  ONBn_fine: 200
  OFFBn_coarse: 4
  OFFBn_fine: 0
  RefrBp_coarse: 4
  RefrBp_fine: 25
  state: false
  name: ''
# no documentation available for this property
davis_biases_aps:
  ADC_RefHigh_volt: 0
  ADC_RefHigh_curr: 0
  ADC_RefLow_volt: 0
  ADC_RefLow_curr: 0
  state: false
  name: ''
# ***************************
# **** Device Properties ****
# ***************************
driver_config:
  streaming_rate: 30
  max_events: 0
  aps_enabled: true
  dvs_enabled: true
  imu_enabled: true
  autoexposure_enabled: true
  autoexposure_gain: 0
  autoexposure_desired_intensity: 0
  exposure: 4000
  frame_mode: 0
  frame_interval: 0
  imu_acc_scale: 3
  imu_gyro_scale: 3
  imu_low_pass_filter: 0
  state: false
  name: ''
# no documentation available for this property
dvs_region_interest:
  roi_start_column: 0
  roi_start_row: 0
  roi_end_column: 0
  roi_end_row: 0
  state: false
  name: ''
# no documentation available for this property
hardware_filters:
  background_activity_filter_enabled: false
  background_activity_filter_time: 0
  refractory_period_enabled: false
  refractory_period_time: 0
  skip_enabled: false
  skip_every: 0
  polarity_suppress: false
  polarity_suppress_type: false
  polarity_flatten: false
  state: false
  name: ''
# no documentation available for this property
imu_calibration_sample_size: 1000
# no documentation available for this property
master: true
# no documentation available for this property
pixel_filter:
  pixel_0_row: 0
  pixel_0_column: 0
  pixel_1_row: 0
  pixel_1_column: 0
  pixel_2_row: 0
  pixel_2_column: 0
  pixel_3_row: 0
  pixel_3_column: 0
  pixel_4_row: 0
  pixel_4_column: 0
  pixel_5_row: 0
  pixel_5_column: 0
  pixel_6_row: 0
  pixel_6_column: 0
  pixel_7_row: 0
  pixel_7_column: 0
  pixel_auto_train: false
  state: false
  name: ''
# no documentation available for this property
reset_timestamps_delay: -1.0

--- name:DAVIS-84010059

# ***************************
# **** Driver Properties ****
# ***************************
serial_number: '84010059'

# Camera intrinsic parameters.
camera_parameters:
  fx: 197.466205
  fy: 197.619274
  cx: 132.572617
  cy: 113.176747
  d0: -0.347401
  d1: 0.123373
  d2: -0.000568
  d3: -0.001087
  width: 240
  height: 180
  ex: .nan
  ey: .nan
  fisheye: false

# no documentation available for this property
acc_bias:
  data:
  - 0.0
  - 0.0
  - 0.0
# no documentation available for this property
gyro_bias:
  data:
  - 0.0
  - 0.0
  - 0.0

